#!/bin/bash

echo ""
echo "=========================================="
echo "  ResuOpti 服务已启动成功!"
echo "=========================================="
echo ""
echo "📱 前端访问地址:"
echo "   http://localhost:5173"
echo ""
echo "🔧 后端服务地址:"
echo "   http://localhost:3000"
echo ""
echo "📚 API 文档 (Swagger):"
echo "   http://localhost:3000/api-docs"
echo ""
echo "🗄️  PostgreSQL 数据库:"
echo "   Host: localhost"
echo "   Port: 15432"
echo "   User: postgres"
echo "   Password: postgres"
echo "   Database: resumopti_dev"
echo ""
echo "=========================================="
echo "💡 常用命令:"
echo "   npm run logs          - 查看所有服务日志"
echo "   npm run logs:backend  - 查看后端日志"
echo "   npm run logs:frontend - 查看前端日志"
echo "   npm run ps            - 查看服务状态"
echo "   npm run stop          - 停止所有服务"
echo "=========================================="
echo ""
